adjective = input('Skriv inn et adjektiv: ')
noun1 = input('Enter a noun')
adjective2 = input('Skriv inn et adjektiv: ')
verb1 = input('Legg til et verb som slutter på ing')
adjective3 = input('Skriv inn et adjektiv: ')

print(f'Today i went to a {adjective} Zoo')
print(f'In an exhibit i saw a {noun1}')
print(f'{noun1} was {adjective2} and {verb1}')
print(f'I was {adjective3}')
